### ISSUE TITLE
Centralize the adding of models.

### ISSUE THREAD

**Issue by boiln** [ztjhz/BetterChatGPT#589]
Please for everyones sake, add a .yml for loading the models.. so you don't have to edit 5555 different locations otherwise an error.

Something like:

```yaml
models:
  - name: 'gpt-4'
    max_tokens: 8000
    cost:
      prompt: { price: 0.0, unit: 1000 }
      completion: { price: 0.0, unit: 1000 }
  - name: 'gpt-4-turbo'
    max_tokens: 128000
    cost:
      prompt: { price: 0.0, unit: 1000 }
      completion: { price: 0.0, unit: 1000 }
  - name: 'gpt-4o'
    max_tokens: 128000
    cost:
      prompt: { price: 0.005, unit: 1000 }
      completion: { price: 0.015, unit: 1000 }
```
